version: '2'
services:
  camundaserver-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/camundaServer/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=camundaServer
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
